/**
 * Provider catalog data — extracted from providers.ts (god-file decomposition).
 * Pure data literal; re-exported by the providers.ts barrel. No behavior change.
 */
export const SEARCH_PROVIDERS = {
  "perplexity-search": {
    id: "perplexity-search",
    alias: "pplx-search",
    name: "Perplexity Search",
    icon: "search",
    color: "#20808D",
    textIcon: "PS",
    website: "https://docs.perplexity.ai/guides/search-quickstart",
    authHint: "Same API key as Perplexity (pplx-...)",
  },
  "serper-search": {
    id: "serper-search",
    alias: "serper-search",
    name: "Serper Search",
    icon: "search",
    color: "#4285F4",
    textIcon: "SP",
    website: "https://serper.dev",
    hasFree: true,
    authHint: "API key from serper.dev dashboard",
    serviceKinds: ["webSearch"],
  },
  "brave-search": {
    id: "brave-search",
    alias: "brave-search",
    name: "Brave Search",
    icon: "travel_explore",
    color: "#FB542B",
    textIcon: "BR",
    website: "https://brave.com/search/api",
    hasFree: true,
    authHint: "Subscription token from Brave Search API dashboard",
  },
  "exa-search": {
    id: "exa-search",
    alias: "exa-search",
    name: "Exa Search",
    icon: "neurology",
    color: "#1E40AF",
    textIcon: "EX",
    website: "https://exa.ai",
    hasFree: true,
    authHint: "API key from dashboard.exa.ai",
    serviceKinds: ["webSearch", "webFetch"],
  },
  "tavily-search": {
    id: "tavily-search",
    alias: "tavily-search",
    name: "Tavily Search",
    icon: "manage_search",
    color: "#5B4FDB",
    textIcon: "TV",
    website: "https://tavily.com",
    hasFree: true,
    authHint: "API key from app.tavily.com (format: tvly-...)",
    serviceKinds: ["webSearch", "webFetch"],
  },
  "google-pse-search": {
    id: "google-pse-search",
    alias: "google-pse",
    name: "Google Programmable Search",
    icon: "travel_explore",
    color: "#4285F4",
    textIcon: "GP",
    website: "https://developers.google.com/custom-search/v1/overview",
    authHint: "Requires a Google API key and your Programmable Search Engine ID (cx)",
  },
  "linkup-search": {
    id: "linkup-search",
    alias: "linkup",
    name: "Linkup Search",
    icon: "public",
    color: "#0F766E",
    textIcon: "LU",
    website: "https://docs.linkup.so",
    authHint: "Bearer API key from the Linkup dashboard",
  },
  "searchapi-search": {
    id: "searchapi-search",
    alias: "searchapi",
    name: "SearchAPI",
    icon: "manage_search",
    color: "#2563EB",
    textIcon: "SA",
    website: "https://www.searchapi.io/docs/google",
    authHint: "API key from SearchAPI (query param or Bearer auth)",
  },
  "youcom-search": {
    id: "youcom-search",
    alias: "youcom-search",
    name: "You.com Search",
    icon: "travel_explore",
    color: "#2563EB",
    textIcon: "YOU",
    website: "https://you.com/business/api/",
    authHint: "X-API-Key from the You.com platform dashboard",
  },
  "searxng-search": {
    id: "searxng-search",
    alias: "searxng",
    name: "SearXNG Search",
    icon: "search",
    color: "#1A237E",
    textIcon: "SX",
    website: "https://docs.searxng.org",
    hasFree: true,
    authHint:
      "API key is optional. Set your SearXNG base URL. Some instances may require a bearer token for access.",
  },
  "ollama-search": {
    id: "ollama-search",
    alias: "ollama-search",
    name: "Ollama Search",
    icon: "search",
    color: "#58A6FF",
    textIcon: "OS",
    website: "https://ollama.com/settings/keys",
    authHint: "Same API key as Ollama Cloud (from ollama.com/settings/keys)",
  },
  "zai-search": {
    id: "zai-search",
    alias: "zai-search",
    name: "Z.AI Coding Plan Search",
    icon: "search",
    color: "#8B5CF6",
    textIcon: "ZAI",
    website: "https://z.ai",
    authHint: "Same API key as Z.AI.",
  },
  "parallel-search": {
    id: "parallel-search",
    alias: "parallel-search",
    name: "Parallel Search",
    icon: "manage_search",
    color: "#111827",
    textIcon: "PA",
    website: "https://parallel.ai",
    hasFree: true,
    authHint: "X-API-Key from the Parallel dashboard.",
  },
  "firecrawl-search": {
    id: "firecrawl-search",
    alias: "firecrawl-search",
    name: "Firecrawl Search",
    icon: "manage_search",
    color: "#F97316",
    textIcon: "FC",
    website: "https://firecrawl.dev",
    hasFree: true,
    authHint: "Bearer API key from the Firecrawl dashboard.",
  },
  "gemini-grounded-search": {
    id: "gemini-grounded-search",
    alias: "gemini-grounded-search",
    name: "Gemini Grounded Search",
    icon: "travel_explore",
    color: "#4285F4",
    textIcon: "GG",
    website: "https://ai.google.dev/gemini-api/docs/grounding",
    authHint: "Same API key as Gemini.",
  },
  "duckduckgo-free": {
    id: "duckduckgo-free",
    alias: "duckduckgo-free",
    name: "DuckDuckGo (free)",
    icon: "search",
    color: "#DE5833",
    textIcon: "DDG",
    website: "https://duckduckgo.com",
    hasFree: true,
    authHint: "No credentials required. Used only as a last-resort search fallback.",
  },
};
